version: "2.4"

services:
  mariadb_db:
    image: mariadb:10.6
    volumes:
      - apothiquiz_dev_data:/var/lib/mysql/
    networks:
      - apothiquiz_dev_network
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apothiquizDb
      MYSQL_USER: apothiquizUser
      MYSQL_PASSWORD: apothiquizPassword
    healthcheck:
      test: "exit 0"

  server:
    image: node:14
    container_name: apothiquiz_dev_server
    depends_on:
      mariadb_db:
        condition: service_healthy
    volumes:
      - "./server:/app"
    networks:
      - apothiquiz_dev_network
    working_dir: /app
    command: ["npm", "run", "start:watch"]
    ports:
      - 5035:5035
    environment:
      NODE_ENV: development
      PORT: 5035
      ACCESS_TOKEN_KEY: __ACCESS_TMP__
      REFRESH_TOKEN_KEY: __REFRESH_TMP__
      DB_HOST: mariadb_db
      DB_USER: apothiquizUser
      DB_DATABASE: apothiquizDb
      DB_PASSWORD: apothiquizPassword

  client:
    image: node:14
    container_name: apothiquiz_dev_client
    environment:
      PORT: 3000
      HOST: client
    ports:
      - 3000:3000
    volumes:
      - "./client/:/app/"
    working_dir: /app
    command: ["npm", "start"]
    networks:
      - apothiquiz_dev_network

volumes:
  apothiquiz_dev_data:

networks:
  apothiquiz_dev_network:
    driver: bridge
