version: "2.4"

services:
  mariadb:
    image: mariadb:10.6
    volumes:
      - dev_database:/var/lib/mysql/
    ports:
      - 3306:3306
    env_file:
      - dev.env
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: "mysql --user=root --password=root --execute 'SHOW DATABASES;'"
      interval: 5s
      start_period: 1m

  mariadb-test:
    image: mariadb:10.6
    ports:
      - 3307:3306
    env_file:
      - dev.env
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: "mysql --user=root --password=root --execute 'SHOW DATABASES;'"
      interval: 5s
      start_period: 1m

volumes:
  dev_database:
