/**
 * Here is the expected data for the imported files that we want to test.
 * Each key of this object is an expectation object ( as we can test several files, we can have several expectations objects )
 * in which each key is a classification, a property or a molecules list.
 *
 * For classifications (class & system) object :
 * - all :  the complete (!) list of names of classification values
 * - nodes : A sample of classification values, a node must consist of a name and the list of names of its children
 *
 * Properties consist of a list of values (names only).
 *
 * The list of molecules contains a sample of molecules that we want to test.
 * A molecule must have a key for each classification and property (can be null),
 * and values are strings or an array of strings
 *
 */
export const expectations = {
  firstVersion: {
    numberOfMolecules: 140,
    class: {
      all: [
        "INHIBITEUR DE FUSION",
        "INHIBITEURS DE NEURAMINISASE",
        "ANALOGUES NUCLEOSIDIQUES",
        "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        "INHIBITEUR DE TERMINASE",
        "INHIBITEUR POLYMERASE NS5B",
        "INHIBITEUR NS5A",
        "INHIBITEUR PROTEINE 3A/4",
        "INHIBITEUR DIRECT ADN polymérase virale et transcriptase inverse",
        "INHIBITEURS NON NUCLEOSIDIQUES DE LA TI",
        "INHIBITEUR ENTREE VHB ET HVD",
        "Inhibiteur récepteur NTCP",
        "INHIBITEUR CYP 3A4",
        "INHIBITEUR CCR5",
        "INHIBITEUR DE PROTEASE",
        "INHIBITEUR DE L'INTEGRASE",
        "PENICILLINES",
        "PENICILLINES A",
        "PENICILLINE G",
        "PENICILLINE M",
        "PENICILLINE V",
        "UREIDO-PENICILLINES",
        "PENICILLINES A LARGE SPECTRE",
        "CARBOXYPÉNICILLINES",
        "INHIBITEURS DE Β-LACTAMASES",
        "MONOBACTAM",
        "CARBAPENEMES",
        "INHIBITEUR DE LA DESHYDROPEPTIDASE",
        "CEPHALOSPORINES",
        "CEPHALOSPORINE DE 1ERE GENERATION",
        "CEPHALOSPORINE DE 2NDE GENERATION",
        "CEPHALOSPORINE DE 3EME GENERATION",
        "CEPHALOSPORINE DE 5EME GENERATION",
        "TETRACYCLINES",
        "AMINOSIDE",
        "MACROLIDES",
        "GLYCOPEPTIDES",
        "POLYPEPTIDES",
        "SULFAMIDES",
        "FLUOROQUINOLONE",
        "LINCOSAMIDES",
        "OXAZOLIDINONES",
        "PHENICOLES",
        "Antituberculeux",
        "NITROFURANES",
        "CESTOCIDES",
        "BENZIMIDAZOLES",
        "5-NITRO-IMIDAZOLES",
      ],
      nodes: [
        {
          name: "ANALOGUES NUCLEOSIDIQUES",
          children: ["INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)"],
        },
      ],
    },
    system: {
      all: ["ANTIINFECTIEUX", "ANTIPARASITAIRE", "ANTIBIOTIQUE", "ANTIVIRAL"],
      nodes: [
        {
          name: "ANTIINFECTIEUX",
          children: ["ANTIVIRAL", "ANTIBIOTIQUE", "ANTIPARASITAIRE"],
        },
        { name: "ANTIBIOTIQUE", children: [] },
      ],
    },
    sideEffects: [
      "hypotension orthostatique",
      "Nephrotoxicité",
      "Décoloration dents",
      "Hypoplasie email dentaire",
      "oesophagite",
      "Torsade de pointe",
      "Ototoxicité",
      "Diminution seuil epileptogene",
      "Syndrome serotoninergique",
      "Toxicite hematologique",
    ],
    interactions: ["CYP3A4", "Allongement QT", "Syndrome serotoninergique"],
    indications: [
      "Grippe",
      "Parkinson",
      "VHB",
      "VIH",
      "CMV",
      "VHC",
      "HSV",
      "VZV",
      "EBV",
      "VHD",
      "Infection bacterienne",
      "Paludisme",
      "Protozoocide",
      "Tuberculose",
      "Helminthes",
      "Protozoaires",
      "Bactéries anaérobies",
    ],
    molecules: [
      {
        dci: "TENOFOVIR DISOPROXIL",
        system: "ANTIVIRAL",
        class: "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        indications: ["VHB", "VIH"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        skeletalFormula: null,
        difficulty: "HARD",
      },
      {
        dci: "TINIDAZOLE",
        system: "ANTIPARASITAIRE",
        class: "5-NITRO-IMIDAZOLES",
        indications: ["Protozoaires", "Bactéries anaérobies"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        difficulty: "HARD",
        skeletalFormula: null,
      },
      {
        dci: "AMANTADINE",
        system: "ANTIVIRAL",
        class: "INHIBITEUR DE FUSION",
        indications: ["Grippe", "Parkinson"],
        interactions: [],
        sideEffects: ["hypotension orthostatique"],
        ntr: null,
        difficulty: "HARD",
        skeletalFormula: null,
      },
    ],
  },
  littleSample: {
    numberOfMolecules: 11,
    system: {
      all: ["ANTIINFECTIEUX", "ANTIBIOTIQUE", "ANTIVIRAL"],
      nodes: [
        {
          name: "ANTIINFECTIEUX",
          children: ["ANTIBIOTIQUE", "ANTIVIRAL"],
        },
      ],
    },
    class: {
      all: [
        "INHIBITEUR DE FUSION",
        "INHIBITEURS DE NEURAMINISASE",
        "ANALOGUES NUCLEOSIDIQUES",
        "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        "PENICILLINES A",
        "PENICILLINES",
        "CEPHALOSPORINES",
        "CEPHALOSPORINE DE 1ERE GENERATION",
        "CEPHALOSPORINE DE 2NDE GENERATION",
        "TETRACYCLINES",
        "NITROFURANES",
      ],
      nodes: [],
    },
    indications: ["Grippe", "Infection bacterienne", "VHB", "VIH", "Parkinson"],
    interactions: [],
    sideEffects: [
      "hypotension orthostatique",
      "Décoloration dents",
      "Hypoplasie email dentaire",
      "oesophagite",
    ],
    molecules: [
      {
        dci: "LYMECYCLINE",
        difficulty: "HARD",
        ntr: 0,
        skeletalFormula: null,
        system: "ANTIBIOTIQUE",
        class: "TETRACYCLINES",
        indications: ["Infection bacterienne"],
        sideEffects: ["Décoloration dents", "Hypoplasie email dentaire", "oesophagite"],
        interactions: [],
      },
    ],
  },
  onlyDCI: {
    numberOfMolecules: 140,
    system: {
      all: [],
      nodes: [],
    },
    class: {
      all: [],
      nodes: [],
    },
    indications: [],
    interactions: [],
    sideEffects: [],
    molecules: [
      {
        dci: "AMANTADINE",
        ntr: null,
        difficulty: "HARD",
        skeletalFormula: null,
        system: null,
        class: null,
        indications: [],
        sideEffects: [],
        interactions: [],
      },
      {
        dci: "THIAMPHENICOL",
        ntr: null,
        difficulty: "HARD",
        skeletalFormula: null,
        system: null,
        class: null,
        indications: [],
        sideEffects: [],
        interactions: [],
      },
    ],
  },
  empty: {
    numberOfMolecules: 0,
    system: {
      all: [],
      nodes: [],
    },
    class: {
      all: [],
      nodes: [],
    },
    indications: [],
    interactions: [],
    sideEffects: [],
    molecules: [],
  },
};
