/**
 * Here is the expected data for the imported files that we want to test.
 * Each key of this object is an expectation object ( as we can test several files, we can have several expectations objects )
 * in which each key is a classification, a property or a molecules list.
 *
 * For classifications (class & system) object :
 * - all :  the complete (!) list of names of classification values
 * - nodes : A sample of classification values, a node must consist of a name and the list of names of its children
 *
 * Properties consist of a list of values (names only).
 *
 * The list of molecules contains a sample of molecules that we want to test.
 * A molecule must have a key for each classification and property (can be null),
 * and values are strings or an array of strings
 *
 */
export const expectations = {
  firstVersion: {
    numberOfMolecules: 140,
    class: {
      all: [
        "INHIBITEUR DE FUSION",
        "INHIBITEURS DE NEURAMINISASE",
        "ANALOGUES NUCLEOSIDIQUES",
        "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        "INHIBITEUR DE TERMINASE",
        "INHIBITEUR POLYMERASE NS5B",
        "INHIBITEUR NS5A",
        "INHIBITEUR PROTEINE 3A/4",
        "INHIBITEUR DIRECT ADN polymérase virale et transcriptase inverse",
        "INHIBITEURS NON NUCLEOSIDIQUES DE LA TI",
        "INHIBITEUR ENTREE VHB ET HVD",
        "Inhibiteur récepteur NTCP",
        "INHIBITEUR CYP 3A4",
        "INHIBITEUR CCR5",
        "INHIBITEUR DE PROTEASE",
        "INHIBITEUR DE L'INTEGRASE",
        "PENICILLINES",
        "PENICILLINES A",
        "PENICILLINE G",
        "PENICILLINE M",
        "PENICILLINE V",
        "UREIDO-PENICILLINES",
        "PENICILLINES A LARGE SPECTRE",
        "CARBOXYPÉNICILLINES",
        "INHIBITEURS DE Β-LACTAMASES",
        "MONOBACTAM",
        "CARBAPENEMES",
        "INHIBITEUR DE LA DESHYDROPEPTIDASE",
        "CEPHALOSPORINES",
        "CEPHALOSPORINE DE 1ERE GENERATION",
        "CEPHALOSPORINE DE 2NDE GENERATION",
        "CEPHALOSPORINE DE 3EME GENERATION",
        "CEPHALOSPORINE DE 5EME GENERATION",
        "TETRACYCLINES",
        "AMINOSIDE",
        "MACROLIDES",
        "GLYCOPEPTIDES",
        "POLYPEPTIDES",
        "SULFAMIDES",
        "FLUOROQUINOLONE",
        "LINCOSAMIDES",
        "OXAZOLIDINONES",
        "PHENICOLES",
        "Antituberculeux",
        "NITROFURANES",
        "CESTOCIDES",
        "BENZIMIDAZOLES",
        "5-NITRO-IMIDAZOLES",
      ],
      nodes: [
        {
          name: "ANALOGUES NUCLEOSIDIQUES",
          children: ["INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)"],
        },
      ],
    },
    system: {
      all: ["ANTIINFECTIEUX", "ANTIPARASITAIRE", "ANTIBIOTIQUE", "ANTIVIRAL"],
      nodes: [
        {
          name: "ANTIINFECTIEUX",
          children: ["ANTIVIRAL", "ANTIBIOTIQUE", "ANTIPARASITAIRE"],
        },
        { name: "ANTIBIOTIQUE", children: [] },
      ],
    },
    sideEffects: [
      "hypotension orthostatique",
      "Nephrotoxicité",
      "Décoloration dents",
      "Hypoplasie email dentaire",
      "oesophagite",
      "Torsade de pointe",
      "Ototoxicité",
      "Diminution seuil epileptogene",
      "Syndrome serotoninergique",
      "Toxicite hematologique",
    ],
    interactions: ["CYP3A4", "Allongement QT", "Syndrome serotoninergique"],
    indications: [
      "Grippe",
      "Parkinson",
      "VHB",
      "VIH",
      "CMV",
      "VHC",
      "HSV",
      "VZV",
      "EBV",
      "VHD",
      "Infection bacterienne",
      "Paludisme",
      "Protozoocide",
      "Tuberculose",
      "Helminthes",
      "Protozoaires",
      "Bactéries anaérobies",
    ],
    molecules: [
      {
        dci: "TENOFOVIR DISOPROXIL",
        system: "ANTIVIRAL",
        class: "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        indications: ["VHB", "VIH"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        skeletalFormula: null,
        difficulty: 1,
      },
      {
        dci: "TINIDAZOLE",
        system: "ANTIPARASITAIRE",
        class: "5-NITRO-IMIDAZOLES",
        indications: ["Protozoaires", "Bactéries anaérobies"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        difficulty: 1,
        skeletalFormula: null,
      },
      {
        dci: "AMANTADINE",
        system: "ANTIVIRAL",
        class: "INHIBITEUR DE FUSION",
        indications: ["Grippe", "Parkinson"],
        interactions: [],
        sideEffects: ["hypotension orthostatique"],
        ntr: null,
        difficulty: 1,
        skeletalFormula: null,
      },
    ],
  },
  secondVersion: {
    numberOfMolecules: 492,
    class: {
      all: [
        "INHIBITEUR DE FUSION",
        "INHIBITEURS DE NEURAMINISASE",
        "ANALOGUES NUCLEOSIDIQUES",
        "ANALOGUES NUCLEOTIDIQUES",
        "INHIBITEUR DE TERMINASE",
        "INHIBITEUR POLYMERASE NS5B",
        "INHIBITEUR NS5A",
        "INHIBITEUR PROTEINE 3A/4",
        "INHIBITEUR DIRECT ADN polymérase virale et transcriptase inverse",
        "INHIBITEURS NON NUCLEOSIDIQUES DE LA TI",
        "INHIBITEUR ENTREE VHB ET HVD",
        "INHIBITEUR CYP 3A4",
        "INHIBITEUR CCR5",
        "INHIBITEUR DE PROTEASE",
        "INHIBITEUR DE L'INTEGRASE",
        "PENICILLINES",
        "INHIBITEURS DE ?-LACTAMASES",
        "MONOBACTAM",
        "CARBAPENEMES",
        "INHIBITEUR DE LA DESHYDROPEPTIDASE",
        "CEPHALOSPORINES",
        "TETRACYCLINES",
        "AMINOSIDE",
        "MACROLIDES",
        "GLYCOPEPTIDES",
        "POLYPEPTIDES",
        "SULFAMIDES",
        "FLUOROQUINOLONE",
        "LINCOSAMIDES",
        "OXAZOLIDINONES",
        "PHENICOLES",
        "Antituberculeux",
        "NITROFURANES",
        "CESTOCIDES",
        "BENZIMIDAZOLES",
        "5-NITRO-IMIDAZOLES",
        "Inhibiteur calcique",
        "antagonistes des récepteurs de l'angiotensine II",
        "antagonistes à l’endothéline",
        "bêta-bloquants",
        "diurétiques",
        "inhibiteurs de l'enzyme de conversion",
        "antihypertenseurs ?-bloquants",
        "antihypertenseurs centraux",
        "antiarythmiques",
        "dérivés nitrés et apparentés",
        "sympathomimétiques",
        "normolipémiants",
        "Antalgiques",
        "anti-inflammatoires",
        "Immunosuppresseurs",
        "Antirhumatismale",
        "traitement symptomatique de l'arthrose",
        "antimigraineux",
        "Myorelaxants hors benzodiazépines",
        "antagonistes de l’hormone de croissance",
        "agonistes de l’hormone de croissance",
        "analogues de la somatostatine",
        "agoniste de l’hormone antidiurétique",
        "antagoniste de l’hormone antidiurétique",
        "inhibiteurs de la parathormone",
        "antithyroïdiens",
        "hormones thyroïdiennes",
        "estrogènes",
        "progestatifs",
        "modulateur des récepteurs à la progestérone",
        "antiprogestatif - interruption de grossesse",
        "prostaglandine - interruption de grossesse",
        "analogues de la GnRH",
        "antagonistes GnRH",
        "antagonistes des récepteurs ostrogéniques hypothalamiques",
        "androgènes",
        "antiandrogènes",
        "bisphosphonates",
        "antidiabétique",
        "antiagrégants plaquettaires",
        "thrombolytiques",
        "anticoagulants",
        "?-bloquants à visée urologique",
        "antispasmodiques urinaires",
        "inducteurs de l’érection",
        "Antitussifs – toux sèche",
        "Antitussifs mucolytiques",
        "bêta-2 mimétiques",
        "antagoniste muscariniques",
        "théophylline et dérivés",
        "mucoglycoprotéine",
        "Agonistes des récepteurs 5-HT1",
        "Agonistes des récepteurs 5-HT2",
        "Agonistes des récepteurs 5-HT3",
        "Agonistes des récepteurs 5-HT4",
        "Agonistes des récepteurs 5-HT5",
        "Agonistes des récepteurs 5-HT6",
        "Agonistes des récepteurs 5-HT7",
        "analgésiques de palier I",
        "analgésiques morphiniques de palier II",
        "analogies du glucagon like peptide-1",
        "analogue de la prostacycline",
        "antagoniste des récepteurs alpha-2",
        "antagoniste H1, D, M",
        "antagonistes des révepteurs GP IIb/IIIa",
        "Antagonistes H1 et 5-HT2",
        "antalgiques de palier II non morphinique",
        "antalgiques morphiniques de palier III",
        "antarythmique de classe I de Vaughan Williams",
        "antarythmique de classe III de Vaughan Williams",
        "antihistaminiques, anticholinergiques",
        "Anti-inflammatoires non stéroïdiens",
        "antipaludéens",
        "anti-TNF alpha",
        "antivitamines K",
        "autres anti-arythmiques",
        "bêta-2 mimétiques d'action courte",
        "bêta-2 mimétiques d'action prolongée",
        "bêta-bloquants cardio-sélectifs",
        "bêta-bloquants non cardio-sélectifs",
        "bêta-bloquants non cardio-sélectifs à action ?-bloquante",
        "biguanide",
        "CARBOXYPÉNICILLINES",
        "central, non opioïde, non antihistaminques",
        "CEPHALOSPORINE DE 1ERE GENERATION",
        "CEPHALOSPORINE DE 2NDE GENERATION",
        "CEPHALOSPORINE DE 3EME GENERATION",
        "CEPHALOSPORINE DE 5EME GENERATION",
        "corticoïdes",
        "Dérivés de l’ergot de seigle",
        "diurétiques d’épargne potassique",
        "diurétiques de l'anse",
        "diurétiques thiazidiques et apparentés",
        "fibrates",
        "glinide",
        "héparines",
        "Inhibiteur calcique ‘à tropisme cardiaque’",
        "Inhibiteur calcique ‘à tropisme vasculaire’",
        "inhibiteur de dihydroorotate déshydrogénase",
        "inhibiteur de l’?-glucosidases",
        "inhibiteur de l’absorption intestinale du cholestérol",
        "inhibiteur de l’IL-17",
        "inhibiteur de l’IL-6",
        "inhibiteur de la captation de l’adénosine dans les plaquettes",
        "inhibiteur de la dihydrofolate réductase",
        "inhibiteur de la dipeptidylpeptidase-4",
        "inhibiteur de la PDE4",
        "Inhibiteur récepteur NTCP",
        "inhibiteurs de la 5-alpha reductase",
        "inhibiteurs de la phosphodiesterase de type 5",
        "inhibiteurs de la sécrétion de l’hormone de croissance",
        "inhibiteurs de l'HMG-CoA réductase",
        "inhibiteurs des Janus Kinase",
        "inhibiteurs des récepteurs P2Y12 plaquettaires",
        "inhibiteurs direct de thrombine",
        "inhibiteurs du facteur Xa",
        "insulines et analogues",
        "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        "INTI (INHIBITEURS NUCLEOTIDIQUES TRANSCRIPTASE INVERSE)",
        "opioïdes",
        "PENICILLINE G",
        "PENICILLINE M",
        "PENICILLINE V",
        "PENICILLINES A",
        "PENICILLINES A LARGE SPECTRE",
        "résines chélatrices",
        "sulfonylurée",
        "sympathomimétiques utilisés par voies IM et IV",
        "sympathomimétiques utilisés par voies orale et/ou nasale",
        "UREIDO-PENICILLINES",
        "acide aminosalicylique et dérivés",
        "acides aminobenzoïques",
        "acides arylacétiques",
        "acides arylpropioniques",
        "antagoniste morphinique",
        "antarythmique de classe II de Vaughan Williams",
        "antarythmique de classe II de Vaughan Williams",
        "antiagrégants plaquettaires",
        "anti-tussif",
        "autres acides arylcarboxylique",
        "Classe IV de Vaughan Williams",
        "glucocorticoïdes",
        "indoliques",
        "insulines d’action intermédiaire",
        "insulines d’action lente",
        "insulines d’action rapide",
        "minéralocorticoïdes",
        "morphiniques agoniste pur",
        "morphiniques agoniste-antagoniste",
        "morphiniques antagoniste partiel",
        "oxicam",
        "sélectifs cox-2",
        "triptans métabolisés par la MAO",
        "triptans métabolisés par la MAO",
        "triptans métabolisés par la MAO",
        "triptans métabolisés par la MAO",
        "triptans non métabolisés par la MAO",
        "triptans non métabolisés par la MAO",
        "triptans non métabolisés par la MAO",
      ],
      nodes: [
        {
          name: "ANALOGUES NUCLEOSIDIQUES",
          children: ["INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)"],
        },
      ],
    },
    system: {
      all: [
        "ANTIINFECTIEUX",
        "Cardio-vasculaire",
        "Douleurs-inflammation",
        "endocrinologie et diabète",
        "hémostase",
        "urologie",
        "Système respiratoire",
        "ANTIVIRAL",
        "ANTIBIOTIQUE",
        "ANTIPARASITAIRE",
        "antihypertenseur",
        "système respiratoire",
        "système respiratoire",
        "hémostase",
        "endocrinologie",
        "diabète",
      ],
      nodes: [
        {
          name: "ANTIINFECTIEUX",
          children: ["ANTIVIRAL", "ANTIBIOTIQUE", "ANTIPARASITAIRE"],
        },
        { name: "ANTIBIOTIQUE", children: [] },
      ],
    },
    sideEffects: [
      "hypotension orthostatique",
      "Nephrotoxicité",
      "Décoloration dents",
      "Hypoplasie email dentaire",
      "oesophagite",
      "Ototoxicité",
      "Torsade de pointe",
      "Diminution seuil epileptogene",
      "Syndrome serotoninergique",
      "Toxicite hematologique",
      "œdème",
      "céphalée",
      "flush",
      "bradycardisant",
      "hyperkaliémiant",
      "torsadogène",
      "hypokaliémiant",
      "hyponatrémiant",
      "ototoxique",
      "toux",
      "sédatif",
      "atropinique",
      "abaisse le seuil épileptogène",
      "à l'origine d'un syndrome sérotoninergique",
      "hypokaliémiants",
      "hyperkaliémiants",
      "néphrotoxiques",
      "néphrotoxique",
      "antabuse",
    ],
    interactions: [
      "CYP3A4",
      "Allongement QT",
      "Syndrome serotoninergique",
      "substrat CYP450",
      "substrat CYP451",
      "substrat CYP452",
      "substrat du CYP450",
      "substrat à risque du CYP450",
      "risque lors d'un sevrage tabagique",
      "substrat à risque du CYP451",
      "substrat à risque du CYP452",
      "substrats à risque du CYP450",
      "substrats à risque du CYP451",
      "substrats à risque du CYP3A4",
      "abaisse le seuil épileptogène",
    ],
    indications: [
      "Grippe",
      "Parkinson",
      "VHB",
      "VIH",
      "CMV",
      "VHC",
      "HSV",
      "VZV",
      "EBV",
      "VHD",
      "Infection bacterienne",
      "Paludisme",
      "Protozoocide",
      "Tuberculose",
      "Helminthes",
      "Protozoaires",
      "Bactéries anaérobies",
      "HTA",
      "angor",
      "arythmie",
      "insuffisance cardiaque",
      "HTAP",
      "arythmie cardiaque",
      "sevrage aux opiacés",
      "douleurs",
      "analgésie pendant l'anesthésie",
      "toux sèche",
      "traitement de substitution",
      "sevrage alcoolique",
      "dépression respiratoire due aux opiacés",
      "associée à la buprénorphine pour empêcher l'utilisation IV",
      "fièvre",
      "ménorragies",
      "rhumatismes, arthroses",
      "Dysménorrhées",
      "antiagrégant",
      "rectocolite hémorragique",
      "rectocolite hémorragique / maladie de Crohn",
      "insuffisance corticosurrénalienne",
      "otites",
      "asthme/BPCO",
      "rhinite allergique",
      "prévention du rejet de greffe",
      "polyarthrite rhumatoïde",
      "cancers",
      "arthrose",
      "migraine",
      "contractures musculaires",
      "sevrage alcolique",
      "acromégalie",
      "retard de croissance",
      "maladie de Cushing",
      "diabète insipide",
      "énurésie nocturne",
      "polykystoses rénales",
      "syndromes de sécrétion inappropriée d'hormone antidiurétique (SIADH)",
      "Hyperparathyroïdie",
      "cancer de la parathyroïde",
      "hyperthyroïdie",
      "hypothyroïdie",
      "freinage de la sécrétion de TSH",
      "traitement hormonal substitutif",
      "prévention de l'ostéoporose",
      "contraception",
      "atrophie vaginale due à une déficience en oestrogènes",
      "insuffisance en progestérone",
      "endométriose",
      "dysménorrhée",
      "contraception d'urgence",
      "cancer hormono-dépendant",
      "interruption de grossesse",
      "cancer de la prostate",
      "puberté précoce",
      "fécondation in vitro",
      "stérilité par anovulation / dysovulation",
      "déficit endrogénique",
      "aplasie médulaire",
      "hypertrophie bénigne de la prostate",
      "alopécie androgénique",
      "diabète de type II",
      "diabète de type I",
      "Prévention des accidents thrombo-emboliques",
      "réduction d'événement thrombotique",
      "infarctus du myocarde",
      "ischémie chronique dévère des membres inférieurs",
      "phénomènes de Raynaud en évolution",
      "traitement des cathéters veineux centraux occlus",
      "IDM",
      "thrombus",
      "purpura thrombopénique",
      "thrombopénie induite par l’héparine",
      "thrombose veineuse profonde",
      "embolie pulmonaire",
      "hyperactivités vésicales",
      "dysfonction érectile",
      "toux productive",
      "asthme",
      "BPCO",
      "travail prématurée",
    ],
    molecules: [
      {
        dci: "TENOFOVIR DISOPROXIL",
        system: "ANTIVIRAL",
        class: "INTI (INHIBITEURS NUCLEOTIDIQUES TRANSCRIPTASE INVERSE)",
        indications: ["VHB", "VIH"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        skeletalFormula: null,
        difficulty: 1,
      },
      {
        dci: "TINIDAZOLE",
        system: "ANTIPARASITAIRE",
        class: "5-NITRO-IMIDAZOLES",
        indications: ["Protozoaires", "Bactéries anaérobies"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        difficulty: 1,
        skeletalFormula: null,
      },
      {
        dci: "AMANTADINE",
        system: "ANTIVIRAL",
        class: "INHIBITEUR DE FUSION",
        indications: ["Grippe", "Parkinson"],
        interactions: [],
        sideEffects: ["hypotension orthostatique"],
        ntr: null,
        difficulty: 1,
        skeletalFormula: null,
      },
      {
        dci: "octréotide",
        system: "endocrinologie",
        class: "inhibiteurs de la sécrétion de l’hormone de croissance",
        indications: ["acromégalie"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        difficulty: 1,
        skeletalFormula: null,
      },
    ],
  },
  littleSample: {
    numberOfMolecules: 11,
    system: {
      all: ["ANTIINFECTIEUX", "ANTIBIOTIQUE", "ANTIVIRAL"],
      nodes: [
        {
          name: "ANTIINFECTIEUX",
          children: ["ANTIBIOTIQUE", "ANTIVIRAL"],
        },
      ],
    },
    class: {
      all: [
        "INHIBITEUR DE FUSION",
        "INHIBITEURS DE NEURAMINISASE",
        "ANALOGUES NUCLEOSIDIQUES",
        "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        "PENICILLINES A",
        "PENICILLINES",
        "CEPHALOSPORINES",
        "CEPHALOSPORINE DE 1ERE GENERATION",
        "CEPHALOSPORINE DE 2NDE GENERATION",
        "TETRACYCLINES",
        "NITROFURANES",
      ],
      nodes: [],
    },
    indications: ["Grippe", "Infection bacterienne", "VHB", "VIH", "Parkinson"],
    interactions: [],
    sideEffects: [
      "hypotension orthostatique",
      "Décoloration dents",
      "Hypoplasie email dentaire",
      "oesophagite",
    ],
    molecules: [
      {
        dci: "LYMECYCLINE",
        difficulty: 1,
        ntr: 0,
        skeletalFormula: null,
        system: "ANTIBIOTIQUE",
        class: "TETRACYCLINES",
        indications: ["Infection bacterienne"],
        sideEffects: ["Décoloration dents", "Hypoplasie email dentaire", "oesophagite"],
        interactions: [],
      },
    ],
  },
  onlyDCI: {
    numberOfMolecules: 140,
    system: {
      all: [],
      nodes: [],
    },
    class: {
      all: [],
      nodes: [],
    },
    indications: [],
    interactions: [],
    sideEffects: [],
    molecules: [
      {
        dci: "AMANTADINE",
        ntr: null,
        difficulty: 1,
        skeletalFormula: null,
        system: null,
        class: null,
        indications: [],
        sideEffects: [],
        interactions: [],
      },
      {
        dci: "THIAMPHENICOL",
        ntr: null,
        difficulty: 1,
        skeletalFormula: null,
        system: null,
        class: null,
        indications: [],
        sideEffects: [],
        interactions: [],
      },
    ],
  },
  empty: {
    numberOfMolecules: 0,
    system: {
      all: [],
      nodes: [],
    },
    class: {
      all: [],
      nodes: [],
    },
    indications: [],
    interactions: [],
    sideEffects: [],
    molecules: [],
  },
};
