export const expectations = {
  molecules: {
    numberOfMolecules: 141,
    systems: {
      all: [
        "ANTIINFECTIEUX",
        "ANTIPARASITAIRE",
        "ANTIBIOTIQUE",
        "ANTIVIRAL",
        "ANTIRIEN",
        "TRESNULLE",
      ],
      nodes: [
        {
          name: "ANTIINFECTIEUX",
          parents: [],
        },
        {
          name: "ANTIBIOTIQUE",
          parents: ["ANTIINFECTIEUX"],
        },
      ],
    },
    classes: {
      all: [
        "camion",
        "PLACEBO",
        "INHIBITEUR DE FUSION",
        "INHIBITEURS DE NEURAMINISASE",
        "ANALOGUES NUCLEOSIDIQUES",
        "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
        "INHIBITEUR DE TERMINASE",
        "INHIBITEUR POLYMERASE NS5B",
        "INHIBITEUR NS5A",
        "INHIBITEUR PROTEINE 3A/4",
        "INHIBITEUR DIRECT ADN polymérase virale et transcriptase inverse",
        "INHIBITEURS NON NUCLEOSIDIQUES DE LA TI",
        "INHIBITEUR ENTREE VHB ET HVD",
        "Inhibiteur récepteur NTCP",
        "INHIBITEUR CYP 3A4",
        "INHIBITEUR CCR5",
        "INHIBITEUR DE PROTEASE",
        "INHIBITEUR DE L'INTEGRASE",
        "PENICILLINES",
        "PENICILLINES A",
        "PENICILLINE G",
        "PENICILLINE M",
        "PENICILLINE V",
        "UREIDO-PENICILLINES",
        "PENICILLINES A LARGE SPECTRE",
        "CARBOXYPÉNICILLINES",
        "INHIBITEURS DE Β-LACTAMASES",
        "MONOBACTAM",
        "CARBAPENEMES",
        "INHIBITEUR DE LA DESHYDROPEPTIDASE",
        "CEPHALOSPORINES",
        "CEPHALOSPORINE DE 1ERE GENERATION",
        "CEPHALOSPORINE DE 2NDE GENERATION",
        "CEPHALOSPORINE DE 3EME GENERATION",
        "CEPHALOSPORINE DE 5EME GENERATION",
        "TETRACYCLINES",
        "AMINOSIDE",
        "MACROLIDES",
        "GLYCOPEPTIDES",
        "POLYPEPTIDES",
        "SULFAMIDES",
        "FLUOROQUINOLONE",
        "LINCOSAMIDES",
        "OXAZOLIDINONES",
        "PHENICOLES",
        "Antituberculeux",
        "NITROFURANES",
        "CESTOCIDES",
        "BENZIMIDAZOLES",
        "5-NITRO-IMIDAZOLES",
      ],
      nodes: [
        {
          name: "camion",
          parents: [
            "INTI (INHIBITEURS NUCLEOSIDIQUES TRANSCRIPTASE INVERSE)",
            "ANALOGUES NUCLEOSIDIQUES",
          ],
        },
        {
          name: "CEPHALOSPORINE DE 1ERE GENERATION",
          parents: ["CEPHALOSPORINES"],
        },
      ],
    },
    sideEffects: [
      "hypotension orthostatique",
      "Nephrotoxicité",
      "Décoloration dents",
      "Hypoplasie email dentaire",
      "oesophagite",
      "Torsade de pointe",
      "Ototoxicité",
      "Diminution seuil epileptogene",
      "Syndrome serotoninergique",
      "Toxicite hematologique",
    ],
    interactions: ["CYP3A4", "Allongement QT", "Syndrome serotoninergique"],
    indications: [
      "Grippe",
      "Parkinson",
      "VHB",
      "VIH",
      "CMV",
      "VHC",
      "HSV",
      "VZV",
      "EBV",
      "VHD",
      "Infection bacterienne",
      "Paludisme",
      "Protozoocide",
      "Tuberculose",
      "Helminthes",
      "Protozoaires",
      "Bactéries anaérobies",
    ],
    molecules: [
      {
        dci: "TENOFOVIR DISOPROXIL",
        system: "ANTIVIRAL",
        class: "camion",
        indications: ["VHB", "VIH"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        skeletalFormula: null,
        levelEasy: null,
        levelHard: null,
      },
      {
        dci: "TINIDAZOLE",
        system: "ANTIPARASITAIRE",
        class: "5-NITRO-IMIDAZOLES",
        indications: ["Protozoaires", "Bactéries anaérobies"],
        interactions: [],
        sideEffects: [],
        ntr: null,
        levelEasy: null,
        levelHard: null,
        skeletalFormula: null,
      },
      {
        dci: "AMANTADINE",
        system: "ANTIVIRAL",
        class: "INHIBITEUR DE FUSION",
        indications: ["Grippe", "Parkinson"],
        interactions: [],
        sideEffects: ["hypotension orthostatique"],
        ntr: null,
        levelEasy: 0,
        levelHard: 1,
        skeletalFormula: null,
      },
    ],
  },
};
