name: Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  build-test-client:
    name: Build and test client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
        working-directory: ./client

      - run: npm run lint
        working-directory: ./client

      - run: npm run format:check
        working-directory: ./client

      - run: npm run build --if-present
        working-directory: ./client

      - run: npm test
        working-directory: ./client
