name: Build and test

on:
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  build-test-client:
    name: Client
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
        working-directory: ./client

      - run: npm run lint
        working-directory: ./client

      - run: npm run format
        working-directory: ./client

      - run: npm run build --if-present
        working-directory: ./client

      - run: npm test
        working-directory: ./client

  build-test-server:
    name: Server
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Stop default mysql server
        run: sudo systemctl stop mysql

      - name: Start mariadb server
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: "10.4.10"
          mysql database: "guacamoleTestDb"
          mysql user: "guacamoleUser"
          mysql password: ${{ secrets.CI_DATABASE_PASS }}

      - run: npm ci
        working-directory: ./server

      - run: npm run lint
        working-directory: ./server

      - run: npm run format
        working-directory: ./server

      - run: npm run build --if-present
        working-directory: ./server

      - name: Setting private key
        run: echo "ACCESS_TOKEN_KEY=TMP_ACCESS_KEY" >> .env; echo "REFRESH_TOKEN_KEY=TMP_REFRESH_KEY" >> .env;
        working-directory: ./server

      - name: Wait for mariadb server to be ready
        env:
          PORT: 3306
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
          docker exec `docker ps -q` mysqld --version

      - run: npm test
        working-directory: ./server
