# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on:
  pull_request:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Shutdown default Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
      - name: Install and setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: "utf8"
          collation server: "utf8_general_ci"
          mysql version: "8.0"
          mysql database: "glowingOctoGuacamole"
          mysql user: "glowing-octo-guacamole-false-user"
          mysql password: ${{ secrets.CI_DATABASE_PASS }}
      - name: Temporise 15s
        run: sleep 15
      - name: Server npm install and test
        run: |
          cd server
          npm ci
          npm run lint
          npm run build --if-present
          npm test
      - name: Client npm install and test
        run: |
          cd client
          npm ci
          npm run lint
          npm run build --if-present
          npm test
        env:
          CI: true
