# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and test

on:
  pull_request:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable and start MySQL
        run: sudo systemctl start mysql.service

      - name: Create and setup database
        run: |
          export MYSQL_PWD=root;
          mysql -uroot -e "CREATE USER 'glowing-octo-guacamole'@'localhost' IDENTIFIED BY '${{ secrets.CI_DATABASE_PASS }}';"
          mysql -uroot -e "CREATE DATABASE glowingOctoGuacamole;"
          mysql -uroot -e "GRANT ALL PRIVILEGES ON glowingOctoGuacamole.* TO 'glowing-octo-guacamole'@'localhost';"
      - name: Server npm install and test
        run: |
          echo "TOKEN_PRIVATE_KEY=TMP_TOKEN_KEY" >> .env
          cd server
          npm ci
          npm run lint
          npm run build --if-present
          npm test
        env:
          CI: true

      - name: Client npm install and test
        run: |
          cd client
          npm ci
          npm run lint
          npm run build --if-present
          npm test
        env:
          CI: true
