name: Build and test the app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Stop default mysql server
        run: sudo systemctl stop mysql

      - name: Start mariadb server
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: "10.4.10"
          mysql database: "glowingOctoGuacamole"
          mysql user: "glowing-octo-guacamole"
          mysql password: ${{ secrets.CI_DATABASE_PASS }}

      - name: Wait for mariadb server to be ready
        env:
          PORT: 3306
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
          docker exec `docker ps -q` mysqld --version

      - name: Server npm install and test
        run: |
          cd server
          echo "TOKEN_PRIVATE_KEY=TMP_TOKEN_KEY" >> .env
          npm ci
          npm run lint
          npm run build --if-present
          npm test
        env:
          CI: true

      - name: Client npm install and test
        run: |
          cd client
          npm ci
          npm run lint
          npm run build --if-present
          npm test
        env:
          CI: true
