name: Deploy to production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd $HOME/glowing-octo-guacamole-prod
            echo "Pulling code"
            git pull origin production
            echo "Building client"
            cd client
            npm install --production
            npm run build
            cd ..
            echo "Updating server"
            cd server
            npm install --production
            echo "Restarting server"
            pm2 restart glowing-octo-guacamole
